services:

  db:
    container_name: postgres22
    image: postgres
    environment:
      POSTGRES_USER: ayoubbenayyad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jwt_security
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  spring-boot-app:
    container_name: pfa-backend
    image: ayoubbenayyad/pfa-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: ayoubbenayyad
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jwt_security

    networks:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
  pfa-frontend:
    container_name: pfa-frontend
    image: ayoubbenayyad/pfa-frontend
    ports:
      - "3000:3000"
    networks:
      - db
    restart: unless-stopped
    depends_on:
      - spring-boot-app


networks:
  db:
    driver: bridge


volumes:
  db:
    name: pfa-backend-db