services:
  db:
    container_name: postgres-sql-docker
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pfa_db_vf
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - pfa-network

  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - pfa-network

  spring-boot-app:
    container_name: pfa-backend
    image: ayoubbenayyad/pfa-backend
    networks:
      - pfa-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pfa_db_vf
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

  pfa-frontend:
    container_name: pfa-frontend
    image: ayoubbenayyad/pfa-frontend
    ports:
      - "3000:3000"
    networks:
      - pfa-network
    restart: unless-stopped
    depends_on:
      - spring-boot-app


networks:
  pfa-network:
    driver: bridge


volumes:
  db: